routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/rooms', 'RoomController@allRooms');
Route::get('/rooms/create', 'RoomController@create')->name('rooms.create');
Route::post('/rooms/create', 'RoomController@store')->name('rooms.store');
Route::get('/rooms/join/{id}', 'RoomController@join')->name('rooms.join');
Route::get('/rooms/{id}', 'RoomController@room')->name('rooms.room');

Route::get('messages', 'RoomController@fetchMessages');
Route::post('messages', 'RoomController@sendMessage');

//TODO delete this (or move to admin middleware)
Route::post('/mc-setting', 'MainController@saveMcServer');
Route::get('/mc', 'MainController@mcIndex');

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin'], function(){
    Route::get('/', 'DashboardController@index')->name('index');

    Route::get('/setting', 'SettingController@index')->name('setting.index');
    Route::post('/setting/store', 'SettingController@store')->name('setting.store');

    Route::post('/setting/setwebhook', 'SettingController@setWebhook')->name('setting.setwebhook');
    Route::post('/setting/getwebhookinfo', 'SettingController@getWebhookInfo')->name('setting.getwebhookinfo');
});

Route::get('/', 'MainController@index')->name('home');

Auth::routes();

Route::get('/home', 'HomeController@index');

Route::get('heroes', 'Hero\MasterHeroController@heroes');

Route::get('/my-heroes', 'HeroController@index')->middleware('player')->name('heroes');
Route::get('/my-heroes/{id}', 'HeroController@show');

Route::get('/skills', 'SkillsController@index')->middleware('master')->name('skills');
Route::post('/skills/create', 'SkillsController@create')->middleware('master');

Route::get('/test', 'TestController@index')->name('test');


Route::post(Telegram::getAccessToken(), function(){
    Telegram::commandsHandler(true);
});

Route::get('/redirect', 'Auth\LoginController@redirectToProvider');
Route::get('/callback', 'Auth\LoginController@handleProviderCallback');

Route::get('logout', 'Auth\LoginController@logout')->name('logout');

resources/views/admin/index.blade.php
@extends('admin.layouts.master')

@section('title')
    Admin / Dashboard
@endsection

@section('content')
    <div class="col s10">
        <h1>
            <span>AdminPanel</span>
        </h1>
    </div>
@endsection

@section('body-scripts')
    <script>
        $( document ).ready(function() {
            $('.collapsible').collapsible();
            $(".dropdown-trigger").dropdown();
        });
    </script>
@endsection

resources/views/admin/setting.blade.php
@extends('admin.layouts.app')

@section('content')
    @if(\Session::has('status'))
        <div class="alert alert-info">
            <span>{{ \Session::get('status') }}</span>
        </div>
    @endif
<div class="container">
    <form action="{{ route('admin.setting.store') }}" method="POST">
        @csrf
        <div class="form-group">
            <label>URL callback for TelegramBot</label>
            <div class="input-group">
                <div class="input-group-btn">
                    <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown"
                            aria-haspopup="true" aria-expanded="false">
                        Действие <span class="caret"></span>
                    </button>
                    <ul class="dropdown-menu">
                        <li><a href="#" onclick="document.getElementById('url_callback_bot').value = '{{ url('') }}'">Вставить url</a></li>
                        <li><a href="#" onclick="event.preventDefault(); document.getElementById('setwebhook').submit();">Отправить url</a></li>
                        <li><a href="#" onclick="event.preventDefault(); document.getElementById('getwebhookinfo').submit();">Получить информацию</a></li>
                    </ul>
                </div>
                <input type="url" class="form-control" id="url_callback_bot" name="url_callback_bot" value="{{ $url_callback_bot ?? '' }}">
            </div>
        </div>

        <button class="btn btn-primary" type="submit">Сохранить</button>
    </form>

    <form id="setwebhook" action="{{ route('admin.setting.setwebhook') }}" method="POST" style="display: none;">
        @csrf
        <input type="hidden" name="url" value="{{ $url_callback_bot ?? '' }}">
    </form>

    <form id="getwebhookinfo" action="{{ route('admin.setting.getwebhookinfo') }}" method="POST" style="display: none;">
        @csrf
    </form>
</div>
@endsection