routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/rooms', 'RoomController@allRooms');
Route::get('/rooms/create', 'RoomController@create')->name('rooms.create');
Route::post('/rooms/create', 'RoomController@store')->name('rooms.store');
Route::get('/rooms/join/{id}', 'RoomController@join')->name('rooms.join');
Route::get('/rooms/{id}', 'RoomController@room')->name('rooms.room');

Route::get('messages', 'RoomController@fetchMessages');
Route::post('messages', 'RoomController@sendMessage');

//TODO delete this (or move to admin middleware)
Route::post('/mc-setting', 'MainController@saveMcServer');
Route::get('/mc', 'MainController@mcIndex');

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin'], function(){
    Route::get('/', 'DashboardController@index')->name('index');

    Route::get('/setting', 'SettingController@index')->name('setting.index');
    Route::post('/setting/store', 'SettingController@store')->name('setting.store');

    Route::post('/setting/setwebhook', 'SettingController@setWebhook')->name('setting.setwebhook');
    Route::post('/setting/getwebhookinfo', 'SettingController@getWebhookInfo')->name('setting.getwebhookinfo');
});

Route::get('/', 'MainController@index')->name('home');

Auth::routes();

Route::get('/home', 'HomeController@index');

Route::get('heroes', 'Hero\MasterHeroController@heroes');

Route::get('/my-heroes', 'HeroController@index')->middleware('player')->name('heroes');
Route::get('/my-heroes/{id}', 'HeroController@show');

Route::get('/skills', 'SkillsController@index')->middleware('master')->name('skills');
Route::post('/skills/create', 'SkillsController@create')->middleware('master');

Route::get('/test', 'TestController@index')->name('test');


Route::post(Telegram::getAccessToken(), function(){
    Telegram::commandsHandler(true);
});

Route::get('/redirect', 'Auth\LoginController@redirectToProvider');
Route::get('/callback', 'Auth\LoginController@handleProviderCallback');

Route::get('logout', 'Auth\LoginController@logout')->name('logout');

resources/views/admin/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js', config('app.env') !== 'local') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css', config('app.env') !== 'local') }}" rel="stylesheet">
</head>
<body>
    <div id="app" class="bg-dark">
        <nav class="navbar navbar-expand-md bg-dark navbar-dark navbar-laravel">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">
                        <li><a href="{{ route('admin.index') }}">Панель состояния</a></li>
                        <li><a href="{{ route('admin.setting.index') }}">Настройки</a></li>
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/admin/layouts/master.blade.php
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>@yield('title')</title>

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <script src="{{ asset('js/jquery-3.4.1.min.js') }}"></script>
    <script src="{{ asset('js/materialize.js') }}"></script>
    <link href="{{ asset('css/materialize.css') }}" rel="stylesheet">
    <link href="{{ asset('css/custom.css') }}" rel="stylesheet">
</head>
<body class="grey darken-2">
<section> <!-- Top menu -->
    <nav class="grey darken-3">
        <div class="container">
            <div class="nav-wrapper">
                <a href="#!" class="brand-logo">DndHelper</a>
                <ul class="right hide-on-med-and-down">
                    <!-- Dropdown Trigger -->
                    <li><a class="dropdown-trigger" href="#!" data-target="dropdown1">{{ \Auth::user()->name }}<i class="material-icons right">arrow_drop_down</i></a></li>
                </ul>
                <!-- Dropdown Content -->
                <ul id="dropdown1" class="dropdown-content grey darken-3">
                    <li class="divider"></li>
                    <li><a href="{{ route('logout') }}">Logout</a></li>
                </ul>
            </div>
        </div>
    </nav>
</section>


<div class="row">
    <div class="col s2">
        <section> <!-- Left Menu -->
            <div class="nav-left">
                <ul class="collapsible">
                    <li class="current">
                        <a href="{{ route('admin.index') }}">
                            <div class="collapsible-header"><i class="material-icons">assignment</i>Dashboard</div>
                        </a>
                    </li>
                    <li>
                        <div class="collapsible-header"><i class="material-icons">public</i>Информация о мирах</div>
                        <div class="collapsible-body">
                            <ul>
                                <li class="element"><a href="">Миры</a></li>
                                <li class="element">Категории миров</li>
                                <li class="element">Страницы</li>
                            </ul>
                        </div>
                    </li>
                    <li>
                        <div class="collapsible-header"><i class="material-icons">speaker_notes</i>Записи</div>
                        <div class="collapsible-body"><span>Lorem ipsum dolor sit amet.</span></div>
                    </li>
                </ul>
            </div>
        </section>
    </div>
    @yield('content')
</div>
@yield('body-scripts')
</body>
</html>